name: Java CI with Gradle. Upload Assets.

on:
  workflow_dispatch

jobs:
  build:
    permissions:
      contents: read
      security-events: read

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin

    - name: Build with Gradle
      run: |
          chmod +x *
          ./gradlew clean build

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: Bot
        path: app/build/libs/*.jar
        
    - name: Upload Assets
      uses: actions/upload-artifact@v4
      with:
        name: Assets
        path: |
          app/*
          !app/*gradle*
          !app/src/
          !app/build/
          !app/logs/