name: Java CI with Gradle. Upload Assets.

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: |
          chmod +x *
          ./gradlew clean build

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: Bot
        path: app/build/libs/*.jar
        
    - name: Upload Assets
      uses: actions/upload-artifact@v4
      with:
        name: Playlists
        path: |
          app/*
          !app/build.gradle.kts
          !app/src/
          !app/build/
          !app/logs/
