name: Java CI with Gradle. Upload Assets.

on:
  workflow_dispatch

jobs:
  build:
    permissions:
      contents: read
      security-events: read

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle
      run: |
          chmod +x *
          ./gradlew clean build

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: Bot
        path: app/build/libs/*.jar
        
    - name: Upload Assets
      uses: actions/upload-artifact@v4
      with:
        name: Assets
        path: |
          app/*
          !app/build.gradle.kts
          !app/src/
          !app/build/
          !app/logs/

  dependency-submission:
    permissions:
      contents: read
      security-events: write

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4

    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v5
